/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.hossain.android.catalogparser

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
